sudo: required
services:
    - docker

before_install:
    - docker build -t kdmalviyan/react_docker -f Dockerfile.dev .

script:
    - docker run -e CI=true kdmalviyan/react_docker npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker_react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-836379380076"
    bucket_path: "docker_react"
    on:
        branch: master
    access_key_id: "$access_key_id"
    secret_access_key: "$secret_access_key"